scenarios8/16_Gates_of_Hell.cfg, scenarios9/01_Transporting_Facility.cfg, scenarios9/48_Execrable_Sanctum.cfg
Abaddon currently does not have his message appear because his unit name is `Abaddon-<random number>`. I have tested this and it fixes the problem.
=> Fix Abaddon missing his message

scenarios10/14_End_of_the_World.cfg, scenarios8/14_Finally_Together.cfg, scenarios8/15_Jungle_Hell.cfg, utils/global_events.cfg, utils/items.cfg
Improves on the sorting of items that was added before. I've gone though and tried to update everywhere that `item_storage` is added to, as currently the item list slowly goes out of order due to unpatched modifications. I have tested all the changed cases except `scenarios10/14_End_of_the_World.cfg` as I don't have a replay of that ATM. It's similar enough to `scenarios8/14_Finally_Together.cfg` that the code should be correct, though.
=> [Requires review] Simplify binary search and try to plug all the holes

utils/help.cfg
For some reason GitHub does not highlight it, but I replaced text
... there will be a trader in a town near the **northern** border ...
with
... there will be a trader in a town near the **southern** border ...
This is scenario 8.8
=> Fixed error in walkthrough

multiplayer/Gladiators.cfg
Spell Eater easily defeats any hero, regardless of resistances, items,
skills, etc. It's game over whenever this boss appears in Gladiators.
We can scale down its HP and damage, but the essence of the problem is
its ranged/melee attacks both being magical, so better just remove it.
=> Gladiators: remove Spell Eater boss as unbalanced

units/Elvish_Juggernaut.cfg
The amla that adds the marksman ability is set to replace specials, when it should append to specials. Fixed.
=> Fix replace to append on marksman ability

utils/items.cfg
Fewer should be used with multiple nouns, but less should be used when singular (in this case the movement point)
=> Grammar fix

utils/utils.cfg
Here is the approach:
1) units with loyal trait are unaffected,
2) every non-loyal unit that appears on the battlefield (regardless of
how it appeared there - [unit], recruit, recall, debug, whatever else)
is marked as upkeep=loyal.
Note: this is invisible (not shown on the unit, unlike "loyal" trait).
3) just in case some unit had some tricky upkeep value (e.g. upkeep=7),
we save the original unit.upkeep into unit.variables.original_upkeep.
4) in the "victory" event, (2) is undone, original upkeeps are restored
and unit.variables.original_upkeep is cleared.
This resolves #8 and #11.
=> Reimplement DISABLE_UPKEEP: temporary unit.upkeep=loyal on placed units

multiplayer/Gladiators.cfg, scenarios8/06_Gladiatrix.cfg, scenarios8/09_Gladiatrix-The_Path_to_Glory.cfg, scenarios8/13_River_of_Flame.cfg
Because ai_formula= no longer works, AI tried to calculate moves for
the "Observers" side in the Gladiators arena.
Replaced with [ai]ai_algorithm=idle_ai[/ai]
=> Replace obsolete parameter "ai_formula=idle_ai" with modern syntax

lua/redeem.lua, utils/amla.cfg
Previously all "Resist [...]" upgrades used the same icon (generic
"leather armor" icon), which didn't look good in redeem menus.
There aren't any distinct anti-pierce/impact/blade armor images,
so their "Resist [...]" upgrades weren't changed (yet).
=> Use icons of anti-ice/fire/arcane armor for "Resist [...]" upgrades

lua.lua
Since "crossbow" matches the "bow$" regex, this regex should be checked
later than comparing to "crossbow" string.
=> "Can equip" check: prevent "crossbow" attack from being treated as bow

multiplayer/Gladiators.cfg
With to_variable= in [unit], the unit never gets placed onto the map.
=> Use [update_stats] in Gladiators without storing unit to a variable

lua/main.lua, lua/stats.lua, lua/titles.lua
Also loti_util_list_attacks() has been simplified, because attack.name is now usable (non-translatable) since the rewrite of stats.cfg.
=> Rename non-unique attack names in update_stats(), e.g. "bow" -> "bow2"

lua/items.lua, lua/main.lua
All methods are documented (purpose, parameters and return values).
Complete list:
```lua
loti.item.storage.add = function(item_number, crafted_sort)
loti.item.storage.remove = function(item_number, crafted_sort)
loti.item.storage.list_items = function(item_sort)
loti.item.storage.list_sorts = function()
loti.item.on_unit.list = function(unit)
loti.item.on_unit.find = function(unit, item_sort)
loti.item.on_unit.add = function(unit, item_number, crafted_sort)
loti.item.on_unit.remove = function(unit, item_number, crafted_sort)
loti.item.on_the_ground.add = function(item_number, x, y, crafted_sort)
loti.item.on_the_ground.remove = function(item_number, x, y, crafted_sort)
loti.item.on_the_ground.list = function(x, y)
loti.item.util.undress_unit = function(unit) …
```
=> Add [lua/items.lua] library for manipulating LotI items in Lua

_main.cfg
This fixes the following warnings on Wesnoth startup:
error deprecation: [campaign]difficulties has been deprecated and will be removed in version 1.15.0. Use [difficulty] instead.
error deprecation: [campaign]difficulty_descriptions has been deprecated and will be removed in version 1.15.0. Use [difficulty] instead.
=> _main.cfg: replace deprecated syntax (in the list of difficulties)

lua/items.lua
Current wording is "ranged attacks only", which would mean it also benefits spells. Writing "melee/ranged weapons only" is more explicit.
=> clarify melee/ranged bonus applies only to weapons

scenarios8/16_Gates_of_Hell.cfg
Because of AI bugs, making Abaddon a leader means he almost never attacks anything. So make him a normal guy and let him stomp the player.
=> AI workaround - let Abaddon attack

scenarios6/15_Apologies.cfg
leader_chosen is never used after this chapter, so get rid of it.
I haven't tested this change.
=> clear leader_chosen

utils/chapter9_utils.cfg
This variable is huge and isn't needed, so clear it.
=> clear unit_list variable

lua/stats.lua
Wesnoth uses integer values for damage and attacks, while lua uses floats. So Guide to Lycanthropy was choosing a 18-5 (damage = 90) attack over a 16-6 (damage = 96) attack, because it was actually seeing 16.85-6 (damage = 101.1) and 18.5-5.75 (damage = 106.375).
=> Fixed damage calculation in bonus attacks.

scenarios7/02_Search_for_Elves.cfg
Allies were not on same team (capitalization appears to matter).
Allies also moved, so now they are set as idle. I'm not sure why they didn't move in the past though.
=> Fix to allies

utils/item_list.cfg
The greater healing potion claims to restore attacks, but currently doesn't. Fix it.
=> Bug: Greater Healing potion should restore attacks

scenarios8/05_Investigations.cfg
I've never liked the way labels appeared in this scenario. They often appear offscreen, so the first time player doesn't even realize that a label's been placed. Even if they do, tracking it down is tedious. With this change, the screen is temporarily scrolled to the goal location and a marker is placed, so the player knows where to go.
I could fold the objectives updates into this too, but I figured I'd see what you thought before I did any more work.
=> UI improvement for Investigations in ch8

utils/global_events.cfg, utils/help.cfg
This covers Beelzebub in a few scenarios, and units that spawn in the walls because the trapdoor/portal hex was occupied.
=> Now collecting items from impassable terrain at the end of the scenario.

lua/main.lua, scenarios3/11_Achilles_Revenge.cfg, scenarios3/12s_Wings_of_Doom.cfg, scenarios3/14_Chasing_Dragons.cfg, scenarios3/15_Nightmare.cfg, scenarios6/15_Apologies.cfg, scenarios7/10_The_Dragon_and_the_Princess.cfg, scenarios7/11_An_Old_Friend.cfg, scenarios7/12_The_Last_Enemy.cfg, scenarios7/14_Arctic_Wastelands.cfg, scenarios7/15_Annihilation.cfg, scenarios8/06_Gladiatrix.cfg, scenarios8/09_Gladiatrix-The_Path_to_Glory.cfg, scenarios8/12_Gladiatrix-The_Reckoning.cfg, scenarios8/16_Gates_of_Hell.cfg
Fixes https://github.com/Dugy/Legend_of_the_Invincibles/issues/233.
The gist of this is to remove titles from units without advancements. That covers everything in the linked issue, plus merchants, flies, spell eaters, etc, etc. I'm open to changing the logic, but I think that's pretty close to how it should be. The only exception I'd make is to give titles to the officers of spawned parties, e.g. infiltrated celestial messengers in Jungle Hell and corrupted elvish juggernauts in Arctic Wasteland. I think the best way to do that is to give them hero icons.
I made sure that unadvanceable nameless units still get names without the titles.
There seems to be a mix of tab and space indentation in this file. I'm a tab man, so I used tabs for this.
=> More selective about giving titles to units.

.editorconfig
[EditorConfig](https://editorconfig.org) helps automatically set the right indentation settings in editors. Supported by many out of the box, and there are plugins for the rest.
=> Added editorconfig.

scenarios1/05_Shatter_the_Defilers.cfg, scenarios1/07_The_Return.cfg, scenarios1/08_Where_the_Sun_Does_not_Shine.cfg, scenarios1/09_Escape_from_Oblivion.cfg, scenarios1/12_Toxic_Sun.cfg, scenarios1/13_Twilight.cfg
I've found some names in chapter 1 weren't marked as translatable. It was probably missed because they didn't require the special treatment for translating into a language with the Latin script.
=> Fixing untranslatable names in the first chapter

scenarios1/12_Toxic_Sun.cfg
Last time didn't notice Efraim's name in "Toxic Sun" being untranslatable
=> Efraim's name made translatable

scenarios1/12_Toxic_Sun.cfg
Sorry for the second pull just in a few minutes, Efraim in the side tag is probably only a notion for testing, the real Efraim is created here when you play the campaign, so it's here his name must be translatable.
=> Efraim's name really made translatable

scenarios7/06_Where_the_Flames_Freeze.cfg
The obelisk is at x=45, but the message triggers between 30 and 40.
=> Fix Beelzebub message in 7_05

scenarios9/43_Verminous_Sewers.cfg
I think I noticed this being odd a long time ago, but suddenly today I dug into it. The random choice to set up an exit on the east side opens terrain in the southwest instead of in the east.
=> Fix eastern exit from Verminous Sewers

utils/global_events.cfg
In the current code it's 2 lvl Elvish Lord who advances straight to the 4 lvl Elvish Overlord. I guess it should be Elvish High Lord receiving such a promotion option
=> Fix of Elvish Lord in multiplayer

units/Lilith.cfg
Lilith had 42x0 attack because of the typo (numbers instead of number).
=> Fixing a typo in Lilith's fireball attack

units/Beelzebub.cfg
He was of a "(none)" race all the way because of this typo
=> Fix a typo in Beelzebub

lua/inventory/storage.lua
The latest fix to disallow unequipping limited items broke unequipping of any item because of missing parentheses
=> Make possible unequipping items

lua/items.lua, lua/main.lua, lua/stats.lua, utils/global_events.cfg, utils/weapons.cfg
As mentioned in #302 we need a unified table of all weapon bindings, so I suggest my solution.
Not exactly a WML resource table, like items' list. I made a special tag `add_weapon_binding` which adds a "name->type" binding to a table `loti.item.weapon_bindings`, then both stats.lua and main.lua use that lua table to determine items' effects and allowed items to gear. Additional bindings are easy to add for other addons using LotI. Also, as mentioned in the issue, I made Drakes' war talon and war blade to be metal claws instead of sword/exotic. Also added cleaver as an axe (in the previous system cleaver has a reversed bug: axe would work for it if equipped but the system doesn't allow to equip it.
My only concern about this solution might be the compatibility with other add-ons using …
=> Weapon bindings system

scenarios5/05_We_Walk_in_the_Shadows.cfg
There was a mismatch between the `[object]` id and the removal id.
=> Lethalia's nightstalk is now removed at the end of ch 5 scen 5.

lua/stats.lua, scenarios1/00_Tutorial.cfg, utils/global_events.cfg
Fix for #313 . Old midgame saves which lack this preload events will still be broken, but only till the end of the scenario.
=> Make weapon bindings be reinitialized using preload

lua/redeem.lua
The soul eater/redeem menu has been unsynchronized which led to negative effects both for MP and watching SP replays. In MP it showed the redeem menu for each player and they all had to choose the same option (or they would get a nasty oos some later), in SP replays it's kinda the same, if your character got a new advancement path, the menu pops up and you have to choose the same option as you had in-game, the choice wasn't remembered in the replay. This should fix that, although old unsynched replays won't work after that (they will show oos "input expected but found something else"
=> Synchronized soul eater/redeem

units/Delly_lich.cfg, units/Vritra.cfg
Spotted in the support topic on the forums
=> Fixing a pair of typos in advancements

lua/titles.lua
The previous code didn't actually looked up the specials, it reached the tag `[specials]` and queried its `id` (which is absent ofc), for actual looking up you need to iterate over `[specials]` children
=> Fix non-working lookup of weapon specials for titles

units/Delly_lich.cfg, units/Delly_start.cfg, units/Forester.cfg, units/Shadowalker.cfg, units/Swordmaster.cfg
I first thought about making it even -50%, but decided to restrain myself a bit and make it 55%. For units with 4 base strikes it makes 1 parry strike, but they got 2 attack after one "parrying better" advancements. For units with 5 base strikes it gives 2 parry strikes. So overall parry becomes beneficial against enemies with 3 or more strikes when you're on a good terrain. Although having 1 parry strikes for units with 4 strikes might seem not very convincing for new players (like doesn't look very powerful), after all I decided that having 2 parry strikes for 4 strikes base attack right from the only advancement is too much (and the only unit with 4 base strikes to have a "parry" advancement is two variations of Delly)
=> Improve parry bonus attacks

utils/global_events.cfg
The only possible optimization I can think of is to make unit variable "got_legacy" and check that variable first instead of scanning modifications every time. Is it needed so much and will it be significant is debatable
=> Legacy assignment made as unit_placed instead of post_stats_update

lua/items.lua, utils/global_events.cfg
So this is my proposal how to fix picking items by AI in mp. We have the "allied_sides" variable. The old DROP macros is implemented backward compatibly, also if "allied_sides" not set the lua code will fall back to the previous mechanism.
=> Fixing item picking by AI sides in multiplayer

utils/global_events.cfg, utils/utils.cfg
For advanced add-on making tweaking global events might prove beneficial, so I think it might be a good idea to split {GLOBAL_EVENTS} a bit into independent blocks, so when an addon maker assembles his global events, he won't have to copypaste all the essential code. A bit changed the order, hope it's not significant.
Also can't find where "recall list items" used, probably it's legacy
And also fixed placed in globals events and utils (gold chests) where players' sides were hardcoded, replaced with $allied_sides as it should be now
=> Modularizing GLOBAL_EVENTS and removing hardcoded allied sides

utils/item_list.cfg
As it doesn't increase the damage of attacks that don't have equippable weapons (such as bite of Dragon Riders), folks asked me to make this kind of clarification
=> Alter a bit the description of Titanic Strength potion

lua/stats.lua
If somehow base_seed isn't set (old code using LotI, for example), Lua will exit with error "can't apply bitwise operations with nil" and the unit disappears
=> Fallback value for base_seed

units/09_Fencer.cfg
I dunno what it was. I just experimented and found that without variation_id's it was bugged as hell. I wonder if Vritra is bugged too, need to check
Maybe it was technically wrong code all the way, but before it didn't bug. I dunno
=> Making Efraim well again

units/Zombie_Rider.cfg
My Zombie Rider has plague (Soulless), greater infect and plague (Monstrosity) all at the same time. The monstrosity plague doesn't work. This seems to fix it.
Note that greater infect is removed when plague (Monstrosity) is added. Not sure if that's desired behavior, but they seem to be incompatible, so that's what I went with.
=> Fixed zombie rider weapon special AMLAs.

scenarios1/09_Escape_from_Oblivion.cfg
That's a bit clunky, tbh, it turns out I just copypasted the macroexpansion reversing the unit to add object on. Initially I wanted just to place this effect on all bats in "unit placed, side 2, Vampire Bat" event but with it the attack menu shows 100% chances. I don't think we want to show the player so obviously that we tweaked the chances about Vampire Bats, do we?
Things are yet to be fixed with bossed of the Bloodbath, although attacking them is a bit extraordinary event by itself
=> Replacement of {FORCE_CHANCE_TO_HIT} in order not to reset stats

scenarios3/06_Darkest_Darkness.cfg
The leader does not appear with type Infernal King. Based on the original change [here](https://github.com/Dugy/Legend_of_the_Invincibles/commit/dea189d37d1d9eb32d989b50a79d6aa4a087f906#diff-a4b7d243ef9cc503109fe1ee2340bf0441107e722c81536a43f53048e0b14dc0R134), I believe this is the intended unit type.
Found in:
Wesnoth 1.16
LotI 3.2.6.222gb6ec4a5
=> Switch Infernal King leader to Infernal Knight

extra_advancements.cfg, utils/global_events.cfg
post advance now needed only for MP
=> Enable Soulless to Necrophage through the [modify_unit_type] mechanism

utils/global_events.cfg
#390 was still broken for older saves. If the player advanced his AMLA unit without update_started=yes set, it got recalced and the advancement was reverted. Here is a replay with demonstration.
[LotI1-Shadow Empire replay 20220105-062727Bugged.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/7811704/LotI1-Shadow.Empire.replay.20220105-062727Bugged.gz)
The problem is that unit placed event didn't check "updated=yes", only "update_started=yes". But update_started wasn't set before the first bug-related patch https://github.com/Dugy/Legend_of_the_Invincibles/blame/9929fd0778dfa2c06830c819c16ca6c2272095ee/lua/stats.lua#L45 so in the older saves only "updated=yes" is set but "update_started=yes" is not. But if "updated=yes" is set, it means the unit has been updated at least once …
=> Don't run initial update_stats on already updated units

utils/items.cfg
0e06fb78fa64a07481178747ac5ad54991f00aa1 introduced this, and it seems [foreach] somehow reset the change made by [describe_object], as a result descriptions are empty after leaving the cycle
The consequence of this is that traders don't show info about items to buy
Pity I didn't notice it two days ago when I was in another scenario with a trader
=> Reverting one {FOREACH} to [foreach] replacement because traders didn't see descriptions

lua/main.lua
The new function returns (100 - old result) according to https://wiki.wesnoth.org/LuaAPI/UpdatingFrom14
=> Fix resistance_against caused bugs

units/Flower_of_Evil.cfg, utils/abilities.cfg, utils/amla.cfg
Wesnoth has a bug (https://github.com/wesnoth/wesnoth/issues/6466 ) in 1.16 that cumulative leadership doesn't work with value= attribute, but works with add=. It can't be fixed in 1.16, only in 1.17, so replacing value= with add= is the option to fix rn for addons.
=> Fix cumulative leadership (considering Wesnoth bug)

scenarios7/05_Tundra.cfg, units/Ice_Wraith.cfg
Turned out Tundra spawn was broken, with random instead of rand. Also I think we can't provide a list in GENERIC_UNIT macro, so I split them by difficulty
Also Ice Wraith had less hp than Ice Spirit, dunno if that was intentional, buffed a little bit.
Also, I would note that the portrait of Fire Wraith is set for Ice Wrait, not recoloured one, I think you may recolour it or just delete the portrait for the unit
=> Little fixes for Ice Wraith

scenarios1/00_Tutorial.cfg
The latest fix was only for 1.17 item system bug. The tutorial skip wasn't fixed
=> Fixing skipping tutorial #414

lua/stats.lua
What was a bit troubling for me in the current legacy-assignment scheme is that if you recruit the same unit type on the same castle hex over and over again, they will always have the same legacy. This way it would depend on the id of an individual unit as well. The last byte chosen because unit's ids are normally something like Unittype-67, so the last byte will differ when recruits go sequentially. Of course, the inner perfectionist tells me that it allows only 10 different legacies out of 12 for a unit type on a given hex, but putting a full-scale hash function seems like an overkill, the last byte of id is reasonably simple.
This shouldn't cause OOS in replays unless someone discovers a unit's legacy in the same scenario as he got the unit, but this is not a standard situation
=> Make legacy choice depend on the last byte of unit's id

lua/redeem.lua, scenarios4/08_An_Army_Is_Born.cfg
I chose arctic blast solely for Efraim to retaliate with. Imagine my surprise when it didn't work. I was two AMLA's in when I realized that it wasn't simply weaker than his fireballs. Alter last advancement saved one, but I now have one wasted AMLA and one wasted redeem path.
=> Let the user know which redeem attacks can be used in retaliation

utils/abilities.cfg
if two ABILITY_HEALS_OTHER VALUE added by oject in same unit thi issue will be the same what in https://github.com/Dugy/Legend_of_the_Invincibles/issues/427.
=> this fix is more appropriate for ABILITY_HEALS_OTHER VALUE and other

utils/chapter5_utils.cfg
Instead of writing some extra logic to gracefully remove them, I think we may just update_stats of Efraim and Lethalia at the start of all scenarios? It won't be too much burden, will it?
=> Fix great spells resetting stats if not used in chapter 5

utils/abilities.cfg, utils/abilities_events.cfg
Unforgiving was broken in several ways. First, it didn't reset the variable after 5 turns. Second, in reality it applied to any attack, not only on those unforgiven unit types. And third, on offense it used [harm_loti] without a harmer, so the unit didn't get XP, soul counts, etc (it was considered that the target just died, not killed by the unforgiving attacker)
Also added a comment for recent healing fix, in order not to forget in the future why it's there
=> Fixing unforgiving ability

units/Troll_Boulderlobber.cfg, utils/item_list.cfg
Some stats of items and units depend on the difficulty with QUANTITY macro. But some of them lacked the default number. When used in addons that don't have difficulty levels (so neither EASY, NORMAL or HARD defined) QUANTITY macro doesn't set any value. So items have no effect at all and Boulderlobber has no defined xp threshold for amla
=> Default values for some items and Boulderlobber's xp

utils/amla.cfg
The latest change to amla.cfg closed the tags in the wrong order, so during the macroexpansion it was like
[unit_type]
id=Type
[unit_type]
id=AdvancingType
[/unit_type]
[/unit_type]
so AdvancingType didn't get created and advancement didn't work
=> Advancing- unit types were not created

lua/main.lua
1.16 before and after:
1.17 before:
1.17 after:
This changes are compatible with 1.16 (no visual differences, it looks the same).
Related issues:
https://github.com/wesnoth/wesnoth/issues/7462
https://github.com/wesnoth/wesnoth/issues/7093
=> Fixed indentation on Unit Information for compatibility with 1.17

lua/main.lua
Before, there are non-translatable parts, because they are wrongly belonging to "wesnoth" domain. I have correctly separated the strings that are already in "wesnoth" and the ones that will go to "wesnoth-loti".
I've also tweaked a bit more to make it look better aligned. (related: https://github.com/Dugy/Legend_of_the_Invincibles/pull/449 )
=> Making unit information translatable

lua/inventory/storage.lua, lua/main.lua
Two more omitted strings, which I found. "Equip" already exist as translatable string on another place, but "Use" is new.
=> Use and Equip translatable

scenarios1/08_Where_the_Sun_Does_not_Shine.cfg
Two messages have been sneaked into the prestart event, which has this undesired effect. Moved to start, immediately after.
=> S08 moved messages from prestart to start

scenarios2/03s_In_the_Magical_Mirror.cfg
As you can see in the image, Efraim is present on this scenario at the bottom, visible if you zoom out or after the victory event. And it's not supposed to be there, not even in secret. With this PR, he will be hidden all the time, from prestart to victory event (and then go straight to recall).
=> Make Efraim hidden on P1-C2-S3

scenarios2/05_Umbra.cfg
This message:
`"Damn those two liches! They will make this battle turn against us!"`
Can be triggered by the dwarves, before the liches has a chance to enter the caverns (with luck, even before the arrival of Umbra). It makes more sense if it's a unit from side 1 that triggers the message and turn the tables.
=> Premature message on "Umbra" scenario

scenarios2/10_Lilith.cfg, scenarios4/08_An_Army_Is_Born.cfg, scenarios4/09_The_First_Blow.cfg, scenarios4/17_Any_Means_Necessary.cfg, scenarios8/01_Invasion.cfg, spinoffs/Affably_Evil/units/Krux.cfg, spinoffs/The_Beautiful_Child/units/Manhunter.cfg, units/Vritra.cfg, units/corruption.cfg, utils/amla.cfg, utils/chapter9_utils.cfg
special_id refers to id, and special_type to the tag [plague] (the only case on LOTI).
This message appears on every attack by some characters in debug mode:
Don't worry about compatibility, all three keys have existed since they were created, just special= will be deprecated
=> Changed special= for special_id or special_type

scenarios3/01_Thirst_for_Adventures.cfg
Without this, the conversation will take place by talking to invisible units if there is no unit near the human city.
Also changed trait_loyal + is_hero with trait_loyal_hero on this scenario
=> Clear shroud on Ch3 S01 final conversation

spinoffs/The_Beautiful_Child/scenarios/Ziggurat_Town.cfg
Because of my lack of situational awareness (I didn't notice the shops :smile:), I ran into a bug where you only get the option to enter the ziggurat once. This should fix it (I haven't tested it, but referencing the rest of the file and my rusty WML knowledge give me reasonable confidence this works).
=> Fix moveto onto Ziggurat only working the first time

utils/abilities_events.cfg
This is more reliable on attacks events. Fine on side events, but when active attack is caused by some kind of event or ability, `side_number `is the active side, not the attacker side.
I don't know if there is any event or ability like this in all of LOTI that can interact in this way, since I detected the error with my own addon (Advanced Wesnoth Wars ambush feature), but it doesn't hurt to trust the variables used in these events.
You can compare the before and after here;
Using $side_number
https://user-images.githubusercontent.com/40789364/232260685-38e5a7b7-3d60-4b6d-9820-473fc5625876.mp4
Using $unit.side (don't worry about the lua warning, this video is recorded in debug mode and always appear with [harm_unit_loti])
https://user-images.githubusercontent.com/40789364/232260691-e54b86 …
=> unit.side instead of side_number on attack related events

utils/global_events.cfg
Have you noticed that when you press shift+c and select a unit, you get an error message? So, the hotkey to "Unit info" doesn't work. The error was simple, the filter was badly placed.
=> Fixed hotkey for unit info

utils/abilities_events.cfg
In rare cases, when the unit is already dead and the incinerate event try to do unstore_unit here, you get an error on the screen and various errors in the log:
```
20230428 15:43:48 error engine: failed to auto-store $unit at (39,26)
20230428 15:43:48 error engine: failed to auto-store $unit at (39,26)
20230428 15:43:48 error wml: [unstore_unit]: variable 'unit' doesn't contain unit data
20230428 15:43:48 error engine: failed to auto-store $unit at (39,26)
20230428 15:43:48 error engine: failed to auto-store $unit at (39,26)
20230428 15:43:48 error engine: failed to auto-store $unit at (39,26)
20230428 15:43:48 error engine: failed to auto-store $unit at (39,26)
```
To avoid this, simply use the same method as in the attacker_hits incinerate event, with the conditional
```
[if] …
```
=> Fixed incinerate on defense

utils/abilities_events.cfg
In the case that an Arch Necromancer infects another Arch Necromancer, and the Arch Necromancer dies from the poison on turn_refresh, it becomes walking corpse instead of a lich. This does not happen if he dies from other causes while infected, so it should be considered a bug. I assume necromancy should take precedence.
I also delete two unnecessary fire_event when unit becomes walking corpse. These events are executed as if the killed unit was the walking corpse, when it should be the necromancer. However, these events are not needed in this situation.
=> Necromancy always takes precedence over infected

utils/abilities_events.cfg
Two fixes:
[filter_second] isn't a valid tag on [kill] (no effect deleting them).
Added [secondary_unit] to [kill]. Without this, the unit killed isn't reflected in statistics.
This does not give experience to the assassin (For that is used [harm_unit] with kill=yes), so the mechanic remains the same.
=> Secondary unit on kill events

scenarios4/08_An_Army_Is_Born.cfg, scenarios4/09_The_First_Blow.cfg, scenarios4/17_Any_Means_Necessary.cfg
When a walking corpse is spawned on a plague victim in these scenarios, a ghost is additionally created, but it does not receive the mass_produced variable, resulting in it ending up on the recall list instead of being summoned directly.
=> mass_produced variable on ghost+walking corpse

scenarios4/11_Invasion.cfg
Without this, units are recalled with the status and HP they had when saved to the variable.
infected and petrified are there just in case, but probably not needed
=> prevamp_store restore HP and status

scenarios5/03_Pirates.cfg, utils/help.cfg
Also, the chapter 5 scenario 1 FAQ says that fire guardians don't level up, which is not true, so I'm assuming there was an update time ago where you forgot about these changes.
=> Recall new advancement Fire Wraith

utils/chapter9_utils.cfg
I've noticed recently several complaints that people not getting how to break the cycle in the Last Crusade and proceed on. Someone proposed to remove "Death of Efraim or Lethalia" from lose conditions after some time to make it more obvious. I removed it after the 9th cycle, but maybe you think the other time will be better (if you agree on this change)
=> Remove the lose condition (Death of Efraim or Lethalia) in the Last Crusade from some point

utils/chapter5_utils.cfg
Without this, Soulgate does not support the DISABLE_UPKEEP macro and summoned units will cost upkeep.
[unit] tag (the third option in case there are no units left in valhalla) fires unit_placed by default, so this is only need on [unstore_unit]
=> Soulgate fires event unit_placed

scenarios5/10_Guards_Quarters.cfg, scenarios5/19_Soldiers_Training_Room.cfg, scenarios5/21_Soldiers_Quarters.cfg, scenarios5/27_Power_Station.cfg, scenarios7/15_Annihilation.cfg, utils/chapter5_utils.cfg
> (Before 1.15.4) This is measured in the number of 'frames', and the default is 50. A frame in Wesnoth is usually displayed for around 30ms.
> ([Version 1.15.4 and later only](https://wiki.wesnoth.org/DevFeature)) This is measured in milliseconds.
So 100 ms is clearly insufficient and there is barely time to see anything. Updated to the new default, 5 seconds (5000 ms)
If you prefer another duration, tell me
=> Update [print] duration

units/The_Prince.cfg
In this case it is an error in textdomain, "Prince" and his description does not exist on wesnoth-units, but longsword and thunderstick do, so the textdomains are adjusted.
=> Translatable "Prince" unit

scenarios5/11_Northern_Guardian_Room.cfg, scenarios5/18_Eastern_Guardian_Room.cfg, scenarios5/20_Southern_Guardian_Room.cfg, scenarios5/23_Akulas_Place.cfg
All these scenarios have the same serious error. As all the enemy bosses have the same id, only the last one appears.
=> Fixed tripled enemy id

utils/chapter5_utils.cfg
Simple fix. I realized this when I summoned all the Valhalla units.
=> Soulgate: spawn random units on passable hex

lua/items.lua
Small cosmetic fix, for the case where an item has damage=0 (due to difficulty mode). Now, it just won't display the phrase.
=> Avoid "Damage decreased by 0%"

scenarios10/03_Fimbulwinter.cfg, scenarios5/23_Akulas_Place.cfg, scenarios5/25_Prison.cfg, scenarios6/14_Frozen_Land.cfg, scenarios7/01_Another_Orcish_Assault.cfg, spinoffs/The_Beautiful_Child/units/Bringer_of_Light.cfg, spinoffs/The_Beautiful_Child/units/Bringer_of_Light3.cfg, spinoffs/The_Beautiful_Child/units/Manhunter.cfg, units/Akula_steel.cfg, utils/chapter5_utils.cfg, utils/chapter9_utils.cfg
There are numerous places where `type=` is used instead of `damage_type=` in `[harm_unit]`, so it has no effect and always does the same damage.
=> [harm_unit] type= > damage_type= fix

utils/chapter9_utils.cfg
- Sort the list of units when adding units.  First by name, with the units without names last (assume most players are less interested in unnamed undead units), then by unit type.
- When you don't have enough gold to add to the list, present a message telling you how much you need instead of just not showing the option to add.
- Replaced one {FOREACH} with [foreach] since I was there
=> Sort add units, not enough gold message

utils/chapter9_utils.cfg
Currently, "Add units" includes units that are already on the autorecall list.
There's probably a more elegant way in lua to check if an object is already a member than iterating through the lists, but I couldn't find it.
=> Remove units from add list already on autorecall list

utils/chapter9_utils.cfg
Present autorecall list as ordered list, with units that won't be recalled flagged with oblique font.
I'm a little embarrassed by the "my_message" stuff.  Worked well enough to minimize changes to existing code while testing.  When I tried to move the if i < max_autorecall conditional inside the value block it didn't work any more, and I just don't care enough about style to beat my head against wml to make it pretty.
Trying something new (to me) with branches here, hopefully it makes sense, otherwise I can redo.
=> Autorecall ordered oblique

scenarios6/03_Into_the_Light.cfg
$eater is the variable that uses the soul eater event and is deleted each time, you have to use the variable saved in the unit.
Do you prefer this type of small fixes in different PRs like you told me, or do you prefer me to join them in Part II fixes?
=> "Into the light" scenario - soul eater variable error

utils/abilities_events.cfg
Every time I use purify, I get "error wml: [variable] with missing name=".
Haven't tested this, hopefully it's an obvious one.
=> [variable] with missing name=

utils/utils.cfg
If you undo and redo a recall/recruit with this macro enabled, the game will fail and prompt you to save and exit. You can continue playing normally if you ignore it, but it's better to avoid the error.
=> Disable undo on DISABLE_UPKEEP macro to avoid desynchronizations

lua/stats.lua, utils/abilities_events.cfg
On the one hand, via lua a name and description are also inserted so that it is visible in the weapons in which it is applied.
On the other hand, the event is changed to be a real hit with [harm_unit], made by the attacker, with defense animation, for the same value (20% of the victim's HP). Previously it was an invisible hit and if the unit died it would suddenly disappear with no animation.
=> Improved devastating blow

12_The_Last_Enemy.cfg, scenarios7/01_Another_Orcish_Assault.cfg, scenarios7/05_Tundra.cfg, scenarios7/08_Eruption.cfg, scenarios7/10_The_Dragon_and_the_Princess.cfg, scenarios7/12_The_Last_Enemy.cfg, scenarios7/14_Arctic_Wastelands.cfg, scenarios7/15_Annihilation.cfg
08 format is odd.  I think it's the EARTHQUAKE.
Looks like Lethalia_evasion event and transport units to leader could probably be made into macros.
Did a little cleanup on evasion and eruption.
I don't understand the Lethstore stuff in 12.  Since the {VARIABLE moved 0} is inside the FOREACH/for loop, isn't it always going to be 0 when evaluated?  Guessing this is a typo, and we could use break instead?
Tested one instance of each of the events (on 1.16 this time).
=> {FOREACH} => [foreach]/[for]

lua/stats.lua, utils/abilities_events.cfg
Fixes some things of #525 
- if a unit receives devastating blow while already dead, since the operation involves a variable already gone, this error is thrown, so I add a conditional so that units with 1 or less health do not receive this blow.
- Added in the description "It cannot kill"
- "-20% HP" translatable
- Wrong math operation. The previous subtracts 17%, not 20%
=> Devastating blow fixes

scenarios6/12_The_Library.cfg
It's probably a copy/paste typo. This bug allows Phillip to read a book and activate the phoenix when he is not supposed to do that.
=> The Library - typo on filter keys

scenarios6/14_Frozen_Land.cfg
Instead of a complicated event system, the effect of which is that if you try to attack with a fire attack, the attack does not occur and the unit loses all its attacks instantly.
With this method, the fire attacks disappear for this scenario and that's it.
Also resolves a problem described on #538 with an ocasional lua error (not related with the knockback of the Solid Phoenix)
=> Better removal of fire attacks on Frozen Land

utils/abilities_events.cfg
- Change use of store/unstore to teleport
- check_passability works better inside [teleport] than in [unstore_unit], so it's more bug-proof
- Simplified code
- Immobile units cannot be knockbacked
- Since unstore_unit is not used, the unit dies on the spot if it has 1 or less health, as in the original code, so it can be animated without glitches.
- Resolves #538
=> Improved knockback

scenarios6/14_Frozen_Land.cfg
The new change using [object] gives an insurmountable problem:
If the unit advances or changes weapons to one that gives it a new fire attack, the object doesn't apply to this new attack even if the unit is rebuilt, since according to the developers, objects and advancements are applied in the strict order they were obtained.
So I think it's better to go back to the previous method, simply adding a conditional to prevent any error from appearing on the screen in case unit or second_unit are not present on attack end event.
This is the only change from the old code.
Remember it still has a small inconvenient, but it doesn't affect the balance much:
- The attacker loses all its attacks for trying.
- Both units receives experience as if it had attacked.
Undo #539
=> Undo fire attack removal changes on Frozen Land

utils/abilities_events.cfg, utils/redeeming.cfg
This is the simplest fix for now, as long as the method is not changed. Both are checked, and without using the {FOREACH} macro.
The old code uses direct edits to units variables to avoid rebuilding the unit, but it is still effective in the LOTI context and does not need to be updated, in my opinion. It works fine, and with this it's already treated as any status between scenarios. I play LOTI with various other addons and they mix well, so it's still a robust system even in 1.17
Resolves #544
=> Clear Lethargy/Wrath and Redeem between scenarios

utils/abilities.cfg
Similar to #533 , in this case forgot to specify that they only work in melee.
=> Specify melee in ability descriptions

lua/redeem.lua, scenarios6/15_Apologies.cfg
I swear blizzard used to scatter enemies, kind of like shockwave.  But it doesn't now, and I see no indication it's trying to.
=> typo in Apologies, update blizzard info in redeem

utils/redeeming.cfg
I have realized in the second part how important it is to manage redeem. And it's hard to see the recharge message, so I added a scroll_to_unit and a delay of half a second, just enough to see the message at the same speed as the healing, for example.
I hope you find it useful, it's just a small change that makes the strategy much easier.
https://github.com/Dugy/Legend_of_the_Invincibles/assets/40789364/257bce88-8ea6-444c-bbad-0c5f2d386e22
=> Scroll when Redeem is recharged

lua/utils.lua, utils/global_events.cfg, utils/utils.cfg
This event is triggered when a unit transfered from another side joins you the next scenario and you recall it, undo, then redo. It affects both multi and single player.
Gives exactly the same error as #522 
To avoid disabling undo on ALL recalls I've done a extra filtering (look at the three commits separately, ignore the last one, it's reverted as it was just a test)
- The allow_undo is removed
- Only the units that have the variables to be deleted or analyzed are filtered`*` (to avoid triggering any unit on side 1)
- Added another disable undo in unit placed event
`*` In case you don't know, `glob_on_variable=*` is a special key that works only when filtering wml (not on any tag), for example [filter_wml], and means "check for existence of `variable` with any value (`*`)"
=> Avoid desync problems with recall fresh troops

lua/stats.lua
Units may have a value of vision that is different from their max_moves. If it's the same as the maximal moves, it takes a negative value (from what I see, it's almost always -1 in this case but the game's cpp code checks ``vision < 0`` so I used the same condition just in case instead of my first-thought ``base_vision == -1``)
=> Respect unit's base vision

lua/items.lua
This one in the legacy case caused older saves (like from 1.14) not working in 1.16
=> Revert 1.16-incompatible lua update in legacy case

utils/abilities_events.cfg
I thought "no" was the default option, and I have to explicitly declare it. I have edited the wiki to reflect this circumstance.
Related with #525 
https://wiki.wesnoth.org/index.php?title=DirectActionsWML&type=revision&diff=71498&oldid=71342
=> Fix experience by devastating blow

scenarios9/37_Catacombs_of_Prolonged_Agony.cfg, utils/chapter9_utils.cfg, utils/utils.cfg
In Steelhive, only one portal was active.
All of the portal events had the same id.  
I included the side in the event id, which may be redundant, but I suppose multiple sides could have a portal at the same x,y?
Also, some portal/tombstones were spawning enemies in walls, where you could not hit them.  I only updated code to use this where I could test at the moment, I suspect it might be used elsewhere as well.
=> fix steelhive portals

scenarios7/05_Tundra.cfg, scenarios7/14_Arctic_Wastelands.cfg
At this time, the camp can be built anywhere on the map, even in fog and darkness on the other side of the map.
This is very prone to exploits, so I came up with a simple and logical way, which requires no change in the feature description.
You can simply build the camp if there are any friendly units but NO enemies inside the camp to be built.
https://github.com/Dugy/Legend_of_the_Invincibles/assets/40789364/2148a718-e850-4572-914e-c0ae6b5e8261
=> Logical encampment building

lua/stats.lua
Same method as #530 
Suck is a stackable ability, which can have different values on different weapons, or affect only some weapons. Until now the only way to see it was on the unit info page, but it's more comfortable that way.
=> Suck and spell suck specials table insert

scenarios9/38_Halls_of_Miscreation.cfg, scenarios9/40_Steelhive_Depths.cfg, scenarios9/41_Heart_of_Steelhive.cfg, scenarios9/44_Gathering_Alcove.cfg, scenarios9/46_Sepulcher_of_the_Nefarious.cfg, scenarios9/47_Basilica_of_Imperfection.cfg, scenarios9/50_The_Last_Crusade.cfg, utils/chapter9_utils.cfg, utils/utils.cfg
Removed FOREACH macros
Added MOVE_SIDE_TO macro for code which was used a few times, particularly when Romero shows up.
I think there might be an unrelated issue in chapter9_utils, STATUE_AMBUSH NUMBER.  One or two variables (gender_...) get set in prestart, then cleared in moveto.  What if you don't "moveto"?  No big deal, just wondered why they were hanging around in debug>inspect (also wonder if the seal guardian stores need to be kept once they are defeated).
=> remove FOREACH in chapter 9

units/corruption.cfg
Move, defense, and melee attack of Corrupted Elven Scout and Elven Rider are broken. This fixes it adapting from the originals. Maybe it uses old animations and you forgot to update.
=> Fix animations on corrupted elven scout and rider

lua/unitdata.lua
@edwardspec  and @Dugy that is my touch on the problem that I can propose to your consideration. 
Logic is pretty simple: we check that advancement in the form ``{id = adv_id}``, if it is, we use ``get_type_advancement`` to try to get the full info. If it's not, then it must be the fully spelt advancement, so we just use ``contents`` without touching it. 
I also want to show you the mod (merely a draft but still) that I'm implementing that I mentioned in #560 and which stumbled upon this bug. https://github.com/Discontinuum/LotI_Legacies_and_Books
The mod adds advancements to units that don't have LotI version. It's planned to add all needed legacies and books, for now only fire and ice dragon legacies are implements. 
``events.cfg`` sets up variables containing WML code of advancements …
=> Only request data about advancement if it's in the bare form 

utils/item_list.cfg
I accidentally noticed ``error engine: Invalid color in palette: magenta-`` in the log, and it turned out that all those items, mostly boots were supposed to have different colours, but it was spelt "magenta->colour" instead of "magenta>color' so they were all magenta
=> All these years nobody knew that all those boots (and a couple of gauntlets) were supposed to have different colours

scenarios2/02_Gods.cfg
In discord someone has reported Harry's death off screen (in the shroud) and when they get to town they talk to someone who doesn't answer. With this change, Harry will still speak as first option (tested), but in case of his absence, any of the surviving soldiers from side 2 will do it, and the conversation still makes sense as is.
I think it's almost impossible for them all to die, so this simple change will suffice.
=> Cover case when Harry dies before reach the town

scenarios2/02_Gods.cfg
Resolves #584 
The alliance is hidden, not visible to the player, so it's the easiest way without making it look like the mages are ACTUALLY allied.
I have also fixed the name of the AI aspect, which is old.
What this AI does is that "Specifying scouts not attack whilst scouting" according to the wiki:
https://wiki.wesnoth.org/Formula_AI_Code_Library#Specifying_scouts_not_attack_whilst_scouting
(Keep in mind that it is more than 10 years old)
But it does not prevent them from attacking each other. That's ok. There will be a fight, since they are really enemies between them, but it will be minimized, since they will prefer to explore except to attack side 1.
=> Ally mages with all player enemies except trolls

utils/abilities_events.cfg
With this change we have three advantages:
- Much less code
- Exact heal value on float text(up to max HP)
- If the unit already have max HP no animation is produced
=> Leeches changed to [heal_unit]

lua/items.lua, lua/stats.lua, utils/item_list.cfg
This is the first patch about #577 making alignment and max_attacks using built-in wesnoth.effect implementation. Vision stays the old way for now, I need to test more how it will work in older replays
=> Use built-in wesnoth [effect] for alignment and max_attacks

scenarios5/23_Akulas_Place.cfg, utils/autorecall.cfg, utils/chapter5_utils.cfg
Populated castles of Akula and her minions.
Docked their gold to pay for it.
Fixed a couple places where Manta.id was referred to as Manta, not akulas_sister.  She now autorecalls automatically, as I believe was intended.
I could lower the effect of destroying amps on Akula's HP from 40% to 20% while I'm in there.
Ref #601
=> populate akulas place, fix manta id

utils/utils.cfg
Just moved ground zero for the drops away from the edge of the map, if necessary.
Closes  #596
=> keep bzb drops on map

lua/utils.lua, scenarios10/01_Despair.cfg, scenarios10/03_Fimbulwinter.cfg, scenarios4/13_The_Way_of_Assassins.cfg, scenarios5/05_We_Walk_in_the_Shadows.cfg, scenarios8/05_Investigations.cfg
While working on FOREACH, I found several scenarios that "Make guards/demons wander", so I made a function to handle that.
Broke out is_in_list so it could be used for lua as well as wml
Added support for ^ in is_in_list to handle terrain types
Around these blocks there is usually code which looks like it is supposed to make only units that can't see our team wander, mostly by changing the units' side.  But it's done differently just about each time, or at least it looks that way to me, so I didn't want to tackle that without really understanding what was going on.  It might be worth a look, though I played all of these and they play okay.
BTW, while I was testing 10/01_Despair, I saw these dropped at the beginning:
- 4 scythe, all Exerminators
- 2 armor, both the same
- 2 mace, both …
=> new tag [make_units_wander]

utils/utils.cfg
Buying items from trader was only decrementing the global gold value, not the local gold variable which controlled what you were allowed to buy.
There are too many different trader implementations, IMO.   A project for another day.
=> fix traders allowing credit

scenarios6/09_Across_the_Barren_Land.cfg, scenarios7/05_Tundra.cfg, scenarios7/14_Arctic_Wastelands.cfg, scenarios8/08_The_Desert.cfg, scenarios8/15_Jungle_Hell.cfg, utils/utils.cfg
I left in the configurable leader and interval based on difficulty.  Probably won't be used, but it's there, and  {TELEPORT_TO_LEADER_MENU Efraim 10 10 10} provides exactly the same functionality as there was before.
Everything (initialization, teleport_wait++, cleanup, etc) is encapsulated in the macro, save for updating objectives.
=> use macro for teleport_to_leader

lua/redeem.lua, utils/redeeming.cfg
I took the calculations in redeeming and put the results in a lua table of probabilities, then added a couple tags which return yes/no for a redeem on a target.  I think this version is a lot easier to read.
There were some disagreements between the redeem level descriptions and the results of the WML calculations.  I assumed the calculations were always the intended behaviour and produced correct results.  There should be no difference in the results.
The redeem level descriptions have been updated to reflect actual behaviour.
I did a hundred or so redeem attacks with both redeem level <5 and level >5, while watching the lookup results and spot checking the probabilities were correct.  Also advanced a few times.  All went as planned (eventually, took me awhile to understand why you did …
=> rewrite of redeeming event

scenarios7/10_The_Dragon_and_the_Princess.cfg, scenarios7/12_The_Last_Enemy.cfg, scenarios7/14_Arctic_Wastelands.cfg, scenarios7/15_Annihilation.cfg, units/Uria.cfg, utils/utils.cfg
Move some redundant code into a single macro.
Originally, there was one taunt for the first time (unless you got extremely lucky), and then one for subsequent misses.  I broke that, could fix it, but I don't think it's worth it (I was thinking you pass a message when you want a specific message, or "" to let the macro pick one for you).
I put a variable in a message.  I really like it.  I can take it out.
It looks like only one attacker_misses is getting used.  Reversing the order (so the one time taunt comes first) was the only way to get the taunt event to run (other than commenting out the other one).  This is consistent with the previous version, but probably not what was originally intended.
=> add EVASION macro

lua/crafting.lua
When I fixed loti.item.type.numbers_between, I introduced a side-effect in crafting.
This time I did a search, and nothing else should have been affected.
I still don't like the whole idea of that function.  If you look at item_list.cfg there's a comment that Dugi's Wrath will  have the highest number.  Next you see several items with higher numbers.  Because things change.  Oh well, I used it myself, so who am I to complain?
=> fix crafting side-effect

spinoffs/Affably_Evil/scenarios/05_Dark_Days_Upon_Us.cfg, spinoffs/Affably_Evil/scenarios/06_Krux_the_Saviour.cfg, spinoffs/Affably_Evil/scenarios/07_The_Unforgivable_Abomination.cfg, spinoffs/Affably_Evil/scenarios/09_The_Escape.cfg, spinoffs/Affably_Evil/scenarios/Strych.cfg, spinoffs/Affably_Evil/utils/global_events.cfg, spinoffs/Affably_Evil/utils/utils.cfg, spinoffs/Kill_the_King/scenarios/05_Back_in_the_Game.cfg, spinoffs/The_Beautiful_Child/scenarios/03_To_Tame_a_Land.cfg, spinoffs/The_Beautiful_Child/scenarios/08_Bringing_the_Light.cfg, spinoffs/The_Beautiful_Child/scenarios/Burkes_Castle.cfg, spinoffs/The_Beautiful_Child/scenarios/Crooked_Ravine.cfg, spinoffs/The_Beautiful_Child/scenarios/Faithdome.cfg, spinoffs/The_Beautiful_Child/scenarios/Farborough.cfg, spinoffs/The_Beautiful_Child/scenarios/Thunderhold.cfg, spinoffs/The_Beautiful_Child/scenarios/Valley_Passage.cfg, spinoffs/The_Beautiful_Child/units/Bringer_of_Light.cfg, spinoffs/The_Beautiful_Child/units/Bringer_of_Light2.cfg, spinoffs/The_Beautiful_Child/units/Bringer_of_Light3.cfg, spinoffs/The_Beautiful_Child/units/Exalted_Blackguard.cfg, spinoffs/The_Beautiful_Child/units/Manhunter.cfg, spinoffs/The_Beautiful_Child/utils/global_events.cfg, spinoffs/The_Beautiful_Child/utils/utils.cfg
Looks like wmlindent had a lot to do here.  The only changes I made were to replace the FOREACH loops with for/foreach, and I changed the loop variables in a couple cases that used i for both inner and outer loops (not wrong as I understand it, but IMO it's a lot more readable to just use unique and potentially less error-prone).
I haven't tested any of these.  I'm going to do some other cleanup stuff (have these been brought up to 1.16?  a recent forum comment said no) and then play test.
Ref #621
=> replace FOREACH in spinoffs

spinoffs/The_Beautiful_Child/scenarios/00_Intro.cfg, spinoffs/The_Beautiful_Child/scenarios/04_Marching_into_War.cfg, spinoffs/The_Beautiful_Child/scenarios/05_Coming_of_the_Tide.cfg, spinoffs/The_Beautiful_Child/scenarios/07_Siege_of_Ziggurat.cfg, spinoffs/The_Beautiful_Child/scenarios/08_Bringing_the_Light.cfg, spinoffs/The_Beautiful_Child/scenarios/Burkes_Castle.cfg, spinoffs/The_Beautiful_Child/scenarios/Crooked_Ravine.cfg, spinoffs/The_Beautiful_Child/scenarios/Faithdome.cfg, spinoffs/The_Beautiful_Child/scenarios/Farborough.cfg, spinoffs/The_Beautiful_Child/scenarios/Fertile_Lands.cfg, spinoffs/The_Beautiful_Child/scenarios/Goonville.cfg, spinoffs/The_Beautiful_Child/scenarios/Grey_Hills.cfg, spinoffs/The_Beautiful_Child/scenarios/Thunderhold.cfg, spinoffs/The_Beautiful_Child/scenarios/Valley_Passage.cfg, spinoffs/The_Beautiful_Child/scenarios/Ziggurat_Town.cfg, spinoffs/The_Beautiful_Child/units/Bringer_of_Light.cfg, spinoffs/The_Beautiful_Child/units/Bringer_of_Light2.cfg, spinoffs/The_Beautiful_Child/units/Bringer_of_Light3.cfg, spinoffs/The_Beautiful_Child/units/Shuja.cfg, spinoffs/The_Beautiful_Child/utils/utils.cfg, utils/utils.cfg
Change advance -> advancement
In Crooked Ravine:
- Remove she_brother from brothers_store when killed/defected
- Make most of brothers appearance dialog one time only
- rename quest variable for consistency
Limit main character to one legacy (was two)
Add Konrad II to your party when found
One of the mercs was missing payment when recruited
In Fertile Lands, units killed by secondary effect like that from shockwave interrogate themself, skip that
In Valley Passage, after killing Luke, units that couldn't traverse mountains couldn't traverse mountains.
In final scenario, enemies may block stairway (specifically, if you enter the final room and then leave, they will just keep spawning new units, which does not honor the [ai][avoid]), blocking you from re-entering room.
- Added [avoid], may …
=> tbc updates for 1.16

utils/abilities_events.cfg
Replace $enemy_sides with [enemy_of].  Fixes explosive slow in scenarios where enemy_sides does not include all enemy sides.
Tested on 1.16.9, Lost in Space (against prince's side).
Closes #634
=> enemy_sides -> [enemy_of]

scenarios8/09_Gladiatrix-The_Path_to_Glory.cfg
In Path to Glory, I never got XP for killing the dracolich.  This fixes that case, and another I hadn't noticed.
In each round, when the last unit of side 2 is killed a die event calls enemy_check, which might store side 1 with kill.  If it does so, since the die event has not completed, the XP for the kill goes to the dead instance of the killer.  At least, I'm pretty sure that's what was happening.  So I give them the XP manually.
If a unit dies from a secondary effect, like explosive attacks, no XP is given.
XP now given if a unit dies from incinerate.
enemy_check is also called from new turn "#For the case of something went wrong".  In that case, there's no unit/second, so no one gets XP.
Tested on 1.16.9.  Tested incinerate kill, kill w/o advancement, kill with one or more …
=> fix missing XP

_main.cfg
The recent change of the second campaign's id breaks the compatibility with older saves: they load but players can no longer change difficulty mid-campaign. I myself had to change difficulty when I played LotI first time, so keeping that working is necessary in my opinion. IDs aren't seen by players anyway (except when in debug mode, which is not the mod in which most players play anyway), and being able to change difficulty is more important
=> Keep the old id to preserve compatibility with old saves

lua/stats.lua
Playing in a custom era, I found some unit being unrecruitable because of a lua error in stats.lua:572. The unit had a ``[damage]`` weapon special without id which caused the code to fail (match receieved nil as the 1st arg)
=> Fix nil error if [damage] special lacks id

scenarios8/08_The_Desert.cfg
It prevents the leader from recruiting when they do. They can still spawn on castle tiles, which reduces the amount a leader can recruit.
=> In ch8 scenario The Desert, undead no longer spawn on keeps.

utils/abilities_events.cfg
This happened to me not too long ago.
1. Efraim got dazzled on turn 61, side turn 11.
2. I finished the scenario on turn 62, side turn 1.
3. Turn 62, side turn 11 never ran, so dazzle wasn't removed. It carried over to the next two scenarios before I intervened.
=> Now clearing dazzle on victory.

lua/main.lua
Tested in 1.16.10 and 1.17.25.
Currently get_time_of_day only triggers a warning in debug mode, but I got tired of looking at it.
https://wiki.wesnoth.org/LuaAPI/UpdatingFrom14
=> wesnoth.get_time_of_day > wesnoth.schedule.get_illumination

scenarios3/10_Gehenna.cfg
Kind of guessing what was intended here.  The message was being skipped the way it was.
Tested 1.17.25
=> move skipped message to [story]

units/Demon_Soul.cfg
Tested with 1.16.10 and 1.17.25.
I have no idea if 1.17.4 is the correct version to check, I just copied that from other changes.  I highly doubt it matters since pretty much anyone running 1.17 should be reasonably up to date.
P.S.  Other than some png > webp changes, which I believe are handled automatically (for now?), all of the other images listed in [Compatibility-breaking changes between 1.16 and 1.17/1.18](https://forums.wesnoth.org/viewtopic.php?p=685243#p685243) are up to date.
=> New locations for demon soul images

scenarios7/15_Annihilation.cfg
> map_passable: If x,y are explicitly given and point to a valid on-map location - try to place unit at this location; if the hex is of an impassable terrain for the unit being placed, or is already occupied by another unit, the new unit will be placed in the nearest vacant hex. ([Version 1.13.8 and later only](https://wiki.wesnoth.org/DevFeature)) Deprecated, use placement=map and passable=yes instead.
=> placement=map_passable -> use placement=map and passable=yes

lua/utils.lua
It's not an error, the side could have no units.
=> change error to debug when setting empty side to wander

utils/abilities.cfg
Gave Ef nighwalker in Jungle Hell, at night, and it didn't do anything.  It looks like maybe the terrain type is newer than when this ability was created or something?  From the description, it sounds like we should just match all forest tiles?
Worked when I tested it, but all I know about terrain is what I just looked up.
=> lesser nightstalk forest terrain

scenarios9/33_Pandemonium.cfg
`error wml: [unstore_unit]: variable 'uria_store' doesn't contain unit data
`
Perhaps it would be better to remove the event when you kill her, but I hate testing wml and this works.
=> Don't unstore Uria when she's dead

spinoffs/Affably_Evil/scenarios/01_Incarcerating.cfg
Even with the incarceration limits nudged upward, this one is still stupid hard.  As in I'd be surprised if anyone makes it to the second scenario without giving up.  The enemy is much stronger, with backstab, has ridiculous income, and can sit back and recruit while you really can't.  Your only real chance is to get pretty lucky with the gear and hope the middle leader runs out into traffic at just the right time.
Your ally has a decent income, but he can't recruit fast enough to use the gold (or make up for his losses in battle).  Giving him a couple extra tiles he can recruit from helps, but I still didn't bother to play it through to the end.  Probably need to hardcode some of the initial gear, and definitely lower enemy income (maybe moving some of it to lower base / higher …
=> more castle tiles for the ally

spinoffs/Affably_Evil/scenarios/09_The_Escape.cfg
`20240320 18:43:06 warning unit: Unknown attribute 'hero' discarded.`
Also, the Items menu was not available for her.
I changed this based on what was in the previous scenario and both issues went away.
=> hero -> variables.hero

utils/abilities_events.cfg
Reordered operations so the only-kill-with-1HP and award experience stuff works properly, disabled resting for incinerated units, and added a loop variable since when Lilith is killed it was deleting the default.
Tested v1.19.0-dev (94b71ac95b2-Clean)
Closes #693
=> Fixes to how incinerate handles kills

scenarios2/10_Lilith.cfg
Given the context and the scenario, I'm reasonably sure these just shouldn't exist at all.
=> invalid recruit= entries

lua/stats.lua, scenarios4/13_The_Way_of_Assassins.cfg, scenarios5/05_We_Walk_in_the_Shadows.cfg, spinoffs/The_Beautiful_Child/units/Bringer_of_Light.cfg, spinoffs/The_Beautiful_Child/units/Bringer_of_Light2.cfg, spinoffs/The_Beautiful_Child/units/Bringer_of_Light3.cfg, units/Argan_lich.cfg, units/Celestial_Messenger.cfg, units/Duke.cfg, units/Elvish_Warlord.cfg, units/Fire_Dragon.cfg, units/Goblin_Warbaner.cfg, units/Infernal_Knight.cfg, units/Lich_King.cfg, units/Prophet.cfg, units/Stormrider.cfg, units/The_Prince.cfg, units/corruption.cfg, units/demon_infiltrators.cfg, utils/abilities.cfg, utils/amla.cfg, utils/item_list.cfg
after https://github.com/wesnoth/wesnoth/commit/a17369597c4869938d0a44a70bd9708452c0fd6b, it is possible what abilities
support directly halos image_halo atttribute is usded for give halo to units under influence of abilities when active,
halo_image_self give halo to owner of abilites when active(filter and attribute specific of abilities used like specials wasn't concerned)
=> Move halos to abilities(wesnoth 1.18 and later)

lua/main.lua, lua/recall.lua, utils/utils.cfg
When you recall units from the past (Invasion, Bloodbath, etc) you only get a list of name/type.  It's hard to remember which is which unless you named them just right.  This adds a unit_preview_pane so you can see a lot more info about the units you are considering.
I gave it it's own recall.lua.  I have more recall gui related features in progress, so this isn't (won't be) just a one-off.
tested on 1.19-dev
=> improve recall old units

utils/item_list.cfg
Regardless of any changes I might be working on for hard, this one is just too powerful.
Or it's too cheap to craft, but I like making it weaker instead of more expensive/rare, because it takes up one of a limited number of slots in one unit (particularly E/L)'s inventory.  I wouldn't argue against making it slightly more expensive/rare as well (+1 amythingy or even +1 sapphire?).
I'd even be tempted to give it something like -1MP so you don't just craft 3 or 4 of these and stack them.
=> weaken godless on normal/hard

lua/item_pick.lua
When you are offerred the option to pick up an item, it doesn't understand that the item is part of a set and do the highlighting like in other places.  Now it does.
Somewhere way down on my list of things to do is a "what if?" option for this menu.  Bring up something like side by side copies of Unit Information that show before and after if you picked this item up (including effect of dropping any necessary item of course).  Probably with highlighting.  Or maybe one Unit Info with "diff-style" changes highlighted.  I don't know.
Actually a number of things I'd like to do with Unit Info.  Like making it available in other places (like where I added that unit_preview_pane).  And making weapon specials into tooltips.  And making tooltips for resistances/penetration that show how the …
=> add set item highlight to item_pick

scenarios1/00_Tutorial.cfg, scenarios1/01_An_Orcish_Assault.cfg, scenarios1/02_The_Assassination.cfg, scenarios1/03_Banished.cfg, scenarios1/04_Paradise_Lost.cfg, scenarios1/05_Shatter_the_Defilers.cfg, scenarios1/06_The_Ruins_of_Lost_Empires.cfg, scenarios1/07_The_Return.cfg, scenarios1/08_Where_the_Sun_Does_not_Shine.cfg, scenarios1/09_Escape_from_Oblivion.cfg, scenarios1/12_Toxic_Sun.cfg, scenarios1/13_Twilight.cfg, scenarios1/14_Shadow_Empire.cfg, scenarios1/15_Long_Way_Home.cfg, scenarios1/16_The_Battle_for_Ogira.cfg, units/Mario.cfg, utils/utils.cfg
Other than disabling Mario's advancement to sarge (duke), not much interesting here.  Mostly gold/turns, recruits limited to L1, and some terrain changes intended to protect enemy leaders from fast heroes killing them before they have a chance to recruit (much).  A few minor tweaks to existing levels intended to smooth out a couple areas where some scenarios were much harder than the rest, but nothing major.
I've tested these thoroughly, including playing through into chapter 5 to get a feel for the long term effects of some of the changes (less BZB encounters due to tighter turn limits, hopefully diminished recall list, etc).  Still not where I'd like it, you can still go without losing any non-fodder units, you just have to be really careful now, but enough of a start that I wouldn't …
=> make hard harder (ch1)

units/Power_Generator.cfg, utils/abilities.cfg, utils/abilities_events.cfg
I was under the impression that the power generators were somewhat important, like they did something to weaken Akula.  It actually doesn't look like they do anything (at least not the ones in Power Station), but I already went into the work of beefing them up.  Might have to do something about that.  
Changed damage type to lightning, because it's called lightning and it makes sense.  Increased the damage, 6x3 isn't going to do much this late in part 1, even if it's lightning. 
Added full damage reflect ability.  Originally I wanted high damage when hit by metal weapons, but except for assuming all blade weapons are metal that's kind of hard to do.  So I just made it reflect on melee.  And it's lightning.  Seriously, don't hit stuff with sparks coming out.  This needs a halo.
I wanted to …
=> strength power generators

scenarios5/08_Entrance.cfg, scenarios5/09_Northwestern_Storeroom.cfg, scenarios5/10_Guards_Quarters.cfg, scenarios5/11_Northern_Guardian_Room.cfg, scenarios5/12_Amplificator1.cfg, scenarios5/13_Eastern_Storeroom.cfg, scenarios5/14_Armoury.cfg, scenarios5/15_Amplificator2.cfg, scenarios5/16_Southeastern_Storeroom.cfg, scenarios5/17_Amplificator3.cfg, scenarios5/18_Eastern_Guardian_Room.cfg, scenarios5/19_Soldiers_Training_Room.cfg, scenarios5/20_Southern_Guardian_Room.cfg, scenarios5/21_Soldiers_Quarters.cfg, scenarios5/22_Amplificator4.cfg, scenarios5/23_Akulas_Place.cfg, scenarios5/25_Prison.cfg, scenarios5/26_Library.cfg, scenarios5/27_Power_Station.cfg, scenarios5/28_War_Zone.cfg, utils/chapter5_utils.cfg
I'm sure some little stuff slipped in here, but two main changes (on hard):
1. Your units don't heal when you leave the room.  
2.  When you enter a room, the objectives must be completed before you can go back the way you came in.  In the case of storerooms, you must complete the objectives before you leave at all.  No more stepping out and stepping back in with your army brand new any time you run into a little trouble.  You can still escape if you can make it to a different exit (for now, long term on hard you should probably not have a way out).  Also, every room now has objectives.
I changed the vars, like sc08=1 and sc09=1 to ch5_quests.sc08.done=yes and ch5_quests.sc09.done=yes.  I find this to help a lot when troubleshooting as if they are all under one variable the inspect gui …
=> end tunnel transition abuse on hard

utils/utils.cfg
It bugs me when Lethalia sees the BZB monument and says "Look!" and then replies to herself.  I don't mind when she speaks both parts when touching the monument, but the former case just comes off as odd.  So this addresses that.  Tested as best I can (I'm in ch5 at the moment, can't test with the kids).
I've never cared for the way the monument message triggers work either.  Sometimes, you trigger one and can't even see it.  Other times you can just about walk up to it and not get a message (fixed this in Pits the other day).  Have you ever considered making the moment a unit and using a sighted event?
Looks like wmlindent did some whitespace changes.  And I added a couple ids to events (that helps a LOT when using :inspect).
Set as draft while I think about the kids.
=> improve bzb momument sighted conversation

utils/abilities.cfg
Only works on offense.  Update description, and active_on so the gui will show it inactive on defense.
=> EXPLOSIVE_SLOW description

help/faq.cfg, help/interface.cfg, help/walkthroughs.cfg, utils/global_events.cfg
Removes only about 32KB, but that's almost 9% of my early saves in Toxic Sun, or about 4% of those late in ch5.
It does make for a simple example of how to remove other stuff.
I did not remove the now unneeded utils/help.cfg.
#787
=> load help menu dynamically

lua/main.lua, lua/stats.lua, utils/abilities_events.cfg
I'm not convinced the changes to update_stats are even needed anymore, since the ability special is created if it doesn't exist when it is needed.
Creating the ability on demand also fixed the issue with enemies not being effected by wrath, at least when attacked with lesser lethargy.
I don't see any reason all of the wml setting unit.variables.wrath* can't be moved to [set_wrath_intensity], assuming we can't just get rid of the variables stuff outright.  If not, I should look at how the unit is passed so that we don't need to "unstore" twice.
Fueled by death appears to still only look at positive wrath.
Tested with whirlwind and greater underdraw (lesser lethargy).
See #751
=> fix wrath for enemies, move to abilities

scenarios8/04_Kidnapped.cfg, units/demons_race.cfg, utils/abilities_events.cfg, utils/amla.cfg, utils/chapter9_utils.cfg, utils/item_list.cfg, utils/utils.cfg
Replaced instances of not_living that will break when it is removed.
Soul Eclipse will need to have effects broken into multiple instances (one per status) unless items.lua is updated.
Ref #663
=> replace depr not_living

units/Vritra.cfg
Also, note that in the main GUI if you mouse over her level you see "Oops..." where advancements are supposed to be.
=> correct corruption4 regeneration text

utils/abilities_events.cfg
I didn't know the thief line also had steals by default.  Be nice if they had the ability so we could see it.
Anyway, attacker hits had exterminator, but defender hits had shadowwalker.
=> exterminator steals, not shadowwalker

scenarios6/09_Across_the_Barren_Land.cfg
In Across the Barren Land, there is a message and a note in objectives that you can teleport your units to your leader via a right click menu item. But it  is always added to Efraim even if you have chosen to play Lethalia so in that case you do not have that option. Here is a fix.
=> Teleporting to Lethalia in Across the Barren Land

lua/items.lua, lua/stats.lua, lua/unitdata.lua
I'm surprised by this.  I expected to have to replace things like foo.description with loti.item.type[foo.number].description all over the place, but it seemed to pretty much just work.
I probably left some stuff in that doesn't need to be.  Anything that was a table inside the item stayed.  If you look at the helm on the Duke in the attached you'll see what I mean (is number_required a clue that this table is not needed? or may not be needed if some code changes elsewhere?).
[LotI2-Tunnels of Cruelty Turn 1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/15444847/LotI2-Tunnels.of.Cruelty.Turn.1.gz)
ref #787
=> remove a lot from items stored on unit

lua/items.lua
If this section encounters a status it doesn't understand (like unplaguable), line simply doesn't change.  So for Soul Eclipise, it showed "Immune to Drain" twice.  Maybe you want to add an else line=<I don't understand $part> or whatnot?
=> unplaguable > unplagueable

units/Monstrosity.cfg
I'm not sure this attack is working correctly.  From what I gather from the GUI, it should only be active if the unit ate a WC this turn, but it seems to always be active.
=> fix faster wail

scenarios3/12_Bitter_Swamp.cfg
I was quite surprised to get Warheart when I bought the tome. After a brief look at git blame, I have no idea how this came about.
=> Ch3 Bitter Swamp: buying the Tome of Necromancy now gives you the right item.
