scenarios6/04_I_Hate_You_I_Hate_You_Too.cfg
scenarios6/07_World_Without_Amity.cfg
scenarios6/08_Misguiding_Lives.cfg
scenarios7/03_Corruption.cfg

Spelling and grammar for chapters 6/7

---

scenarios7/04_Last_Survivors.cfg

(at least in American English, you are "pregnant with" the fetus and "pregnant from" the biological father of that fetus)

English improvement

---

scenarios6/13_Phoenix.cfg
scenarios6/14_Frozen_Land.cfg
scenarios7/02_Search_for_Elves.cfg
scenarios8/11_Odd_World.cfg

cash seems to backslide between turns, possibly when villages are taken or lost? Hopefully these patches will fix this for four scenarios. Don't have time right now to edit all scenarios with the text "no matter what it shows". untested

address diminishing money bug?

---

scenarios8/01_Invasion.cfg
scenarios8/04_Kidnapped.cfg
scenarios8/05_Investigations.cfg
scenarios8/06_Gladiatrix.cfg
scenarios8/07_Unimportant_Revolution.cfg
scenarios8/10_Ruins_of_Wesnoth.cfg
scenarios8/12_Gladiatrix-The_Reckoning.cfg
scenarios8/14_Finally_Together.cfg
scenarios8/15_Jungle_Hell.cfg
scenarios8/16_Gates_of_Hell.cfg
units/Shadowalker.cfg
utils/item_list.cfg

Just some grammar changes. Hopefully I have not changed the meaning too much.

Improve chapter 8 messages and some item descriptions

---

units/Argan_lich.cfg
units/Delly_lich.cfg
units/Dwarvish_Technocrat.cfg
units/Krux_later.cfg
units/Lethalia_god.cfg
units/Lethalia_lich.cfg
units/Stormrider.cfg
utils/item_list.cfg

I adjusted my script to print out missing amlas that it couldn't find and this is the result. I'm not 100% sure if I changed the correct thing in each case, but this fixes all of the cases the seem unintended AFAIK. Also finished renaming the Theophrastus Redivivus.

Track down missing amlas and finish renaming started in cadbf10

---

scenarios5/13_Eastern_Storeroom.cfg
scenarios5/14_Armoury.cfg
scenarios5/16_Southeastern_Storeroom.cfg
scenarios5/19_Soldiers_Training_Room.cfg
scenarios5/21_Soldiers_Quarters.cfg
scenarios5/23_Akulas_Place.cfg
scenarios5/25_Prison.cfg
scenarios5/28_War_Zone.cfg

I noticed some scenarios had a possible broken SCENARIO_MUSIC tag. This should fix all the cases.

Fix ogg.ogg extensions

---

scenarios9/05_Stygian_Caverns.cfg
utils/abilities.cfg
utils/chapter9_utils.cfg
utils/item_list.cfg

Just a few changes, nothing major.

Adjust some item descriptions

---

utils/abilities.cfg
utils/item_list.cfg

I should probably get on with some real work...

More item text adjustments

---

units/Mario.cfg

A little something. James_The_Invisible

Fixed a comment for Mario

---

units/Beelzebub.cfg
units/Uria_avatar.cfg
utils/item_list.cfg

I adjusted the wiki script to detect errors like that in #36 and this was what it found.

More inversion corrections

---

utils/global_events.cfg

Changes:
To:
This shouldn't change translatability of anything.

Collapse items of the same type when viewing item storage

---

scenarios1/10_The_Poison.cfg

Apparently being a dragon is just not enough... Discussion at https://forums.wesnoth.org/viewtopic.php?f=8&t=32384&p=619436#p619436

Add flaming radiance to spice Arsenius up

---

units/Efraim_lich.cfg

@Dugy I can't find any uses of this, so can it be removed? Reported here: https://forums.wesnoth.org/posting.php?mode=reply&f=8&t=32384#pr619466

Remove female variation from Efraim

---

scenarios2/05_Umbra.cfg

Not so sure about the preach thing. Still sounds weird to me.

Fix grammar

---

scenarios1/15_Long_Way_Home.cfg

Fix typo in 15_Long_Way_Home.cfg

---

scenarios8/12_Gladiatrix-The_Reckoning.cfg

Give demon leaders traits in scenario 8_12

---

utils/abilities.cfg

Slightly clarify wording of tax collector ability by saying "tax its own side"

clarify tax_collector

---

scenarios7/08s_Neighbours.cfg

"I really though he meant" -> "I really thought he meant"

Fix typo in 08s_Neighbours.cfg

---

scenarios8/04_Kidnapped.cfg

1) th,ey -> they
2) added comma to "when they [...] they"

Fix typo in 04_Kidnapped.cfg

---

units/Orcish_Nightblade.cfg

Fix a typo in the Orchish_Nightblade advancement for kicks

Fix typo in Orchish Nightblade

---

units/undead_demons.cfg

Path to images of Revenant (they are from Wesnoth itself) has changed.

Fix missing sprite image of "Knight of Disaster" unit

---

multiplayer/Gladiators.cfg
utils/utils.cfg

This solves issue #90 (images not showing in "market" menu).

Fix images not being shown in trading menus and "Choose your hero" menu in Gladiators

---

scenarios8/09_Gladiatrix-The_Path_to_Glory.cfg

Add labels to shops in 09_Gladiatrix-The_Path_to_Glory.cfg

---

lua/debug.lua

(wasn't added in efbe43fd1f847f40e1109a02bfc12665c65b2b43)

Add missing lua/debug.lua

---

scenarios5/23_Akulas_Place.cfg

Wrong unit ID: akulas_siter -> akulas_sister

Fix typo in [23_Akulas_Place.cfg]

---

scenarios3/14_Chasing_Dragons.cfg
utils/abilities_events.cfg
utils/item_list.cfg
utils/redeeming.cfg

It was noticed in https://github.com/wesnoth/wesnoth/pull/3790 that these [filter_wml] are superfluous.

Replace [filter_wml] with more efficient filters (status, has_attack)

---

scenarios1/00_Tutorial.cfg

The bug in Tutorial was reported in the forum.
This fix has been tested by completing the Tutorial.

Fix errors in 00_Tutorial caused by [store_unit]kill=yes before [update_stats]

---

lua/stats.lua

Noticed on the forum. (equipped axe wasn't improving Battlerager's attack)

Fix typo in Battlerager's attack name in update_stats()

---

lua/items.lua
scenarios1/08_Where_the_Sun_Does_not_Shine.cfg
scenarios1/10_The_Poison.cfg
utils/utils.cfg

Due to https://github.com/Dugy/Legend_of_the_Invincibles/pull/166#issuecomment-450121239

items.lua: exclude orbs from list_regular(), they can't be unequipped

---

lua/stats.lua

Noticed on the forum (backstab was missing on units).

update_stats(): fix missing backstab

---

lua/titles.lua
scenarios10/14s_New_Era.cfg
scenarios3/01_Thirst_for_Adventures.cfg
utils/amla.cfg
utils/item_list.cfg
utils/titles.cfg

Less incorrect warnings = higher chance to notice warnings that actually found something.

wmllint: make it not complain about some false positives (things that are not errors)

---

units/Elder_Mage.cfg

replace GREATER_AMLA_DEFAULT_BONUS with normal AMLA_DEFAULT_BONUS

fix amla macro usage

---

lua/crafting.lua
lua/items.lua

See the list of commits for details.

Improvements to the new crafting dialog

---

lua/crafting.lua

Resolves the issue noticed in https://github.com/Dugy/Legend_of_the_Invincibles/pull/185#issuecomment-450409975

Crafting dialog: improve UI when switching between Weapons/Armours

---

lua/crafting.lua

This fixes https://github.com/Dugy/Legend_of_the_Invincibles/issues/190

Update the gem counts in Crafting dialog after each Transmute

---

lua/scenario/tutorial.lua

Per the comment in https://github.com/Dugy/Legend_of_the_Invincibles/pull/194#issuecomment-450526344

Tutorial: unhide Transmute button in the crafting dialog

---

lua/items.lua

We need to place image/halo into one overlay (as [item] does in WML),
so that when "pick_item" event removes the image, it removes halo too.

items.lua: on_the_ground.add: fix halo not being removed by "pick_item"

---

lua/items.lua
lua/stats.lua

(crafted gauntlets were adding the same defense as crafted armours)

Fix update_stats() not reducing defense of crafted non-armours

---

lua/items.lua
scenarios10/14_End_of_the_World.cfg
scenarios8/14_Finally_Together.cfg
scenarios8/15_Jungle_Hell.cfg
utils/global_events.cfg
utils/item_list.cfg
utils/items.cfg

Possible solution for issue #188.

Avoid gold in item storage

---

scenarios6/15_Apologies.cfg

I noticed these variables still in my later saved game files and traced them back to here. Also did some tab to space cleanup.
I don't see any flaw here, but I haven't gone more than one scenario ahead.

clear variables and tab to space

---

scenarios10/14_End_of_the_World.cfg

Final scenario did not merge all items

bug fix in item list merge

---

scenarios7/01_Another_Orcish_Assault.cfg
scenarios7/03_Corruption.cfg
scenarios7/04_Last_Survivors.cfg
scenarios7/06_Where_the_Flames_Freeze.cfg
scenarios7/07_Subterranean_War.cfg
scenarios7/08_Eruption.cfg
scenarios7/08s_Neighbours.cfg
scenarios7/09_The_Den_of_Evil.cfg
scenarios7/10_The_Dragon_and_the_Princess.cfg
scenarios7/11_An_Old_Friend.cfg
scenarios7/13_Avengers.cfg

minor cleanup

---

lua/stats.lua

Fix for https://github.com/Dugy/Legend_of_the_Invincibles/issues/224 (also includes deleting some trailing whitespace due to my editor settings)

Fix for issue 224

---

lua/stats.lua

fix removal of GEARED

---

lua/items.lua

tweaking item affect colors

---

scenarios10/14_End_of_the_World.cfg

Apparently it doesn't work in the prestart event but does work in the start event.
I wonder if I'm the only person that ever gets to the end ...

bug fix to make enemy leaders black souls

---

lua/items.lua
lua/stats.lua
lua/unitdata.lua
lua/utils.lua
tests/lua/unitdata.test.lua
utils/items.cfg

See also: issue #204 (discussion of unitdata API), pull request #250 (where unitdata library was added).

Merge unitdata into master branch, step 2: stats.lua + secondary bugfixes

---

utils/chapter9_utils.cfg

It's annoying to take 40 damage before you even have a chance to move.

Infernal tentacles/eyeballs don't take effect on turn 1.

---

units/vampires.cfg

Typo fix in units/vampires.cfg

---

utils/abilities_events.cfg

Fix producer. I thought I fixed this long ago, but clearly not.

Fix producer

---

utils/chapter9_utils.cfg

The demon counter doesn't count for me, and this fixes it.

fix demons_killed

---

utils/item_list.cfg

I've found that Holy Sword has a description directly saying about "Unholy Axe". Evidently it should be the description of Unholy Axe. I guess Unholy Axe's description is the description of Holy Sword, though it doesn't add any lightbeam.

Unholy Axe and Holy Sword descriptions seem to be confused

---

utils/item_list.cfg

Transformed Flesh is listed as Transformed Connectivity Tissue

Fix description of Transformed Flesh

---

units/Vritra.cfg

Fix for #304, tried it till the first variation, seems working (she blinks during a transition but that's okay compared to an incorrect disappearance)

Fix Vritra's corruption logic

---

lua/main.lua

Fix of info menu for units with defence cap

---

lua/item_pick.lua

Fix typo in item pickup

---

multiplayer/Gladiators.cfg

As it's a coop, no need to have shuffle and problems arising from it

Disable shuffle in Gladiators MP scenario

---

scenarios4/12_Bloodbath.cfg

Don't use FORCE_CHANCE_TO_HIT in Bloodbath

---

scenarios1/08_Where_the_Sun_Does_not_Shine.cfg
scenarios1/09_Escape_from_Oblivion.cfg
scenarios1/10_The_Poison.cfg
scenarios1/12_Toxic_Sun.cfg
scenarios6/02_Who_Am_I.cfg
scenarios6/03_Into_the_Light.cfg
scenarios6/04_I_Hate_You_I_Hate_You_Too.cfg

1.16 added a lot of new zombie types, and I think a spider one fits into some cave scenarios. It has a lot of hp (25/36), but I mentioned it only once in lists so it would be rarely recruited

Add a spider zombie to possible variations

---

lua/inventory/dialog.lua
lua/inventory/items.lua
lua/inventory/retaliation.lua
lua/inventory/storage.lua

I tested it a bit, now it seems working. The only problem, dunno if it appeared only now or always was here: sometimes if I click fast I feel like some clicks are skipped and a checkbox doesn't change. The next click it works though

Retaliation window fix

---

utils/global_events.cfg
utils/items.cfg

With this PR I start replacing deprecated FOREACH (which lacks scoping and overall not that fancy) to [foreach] tag, it's enough common so in order to reduce risks it would be bit-by-bit replacement

Replacing deprecated FOREACH macro with [foreach] tag

---

scenarios1/11_Ascension.cfg
scenarios1/12_Toxic_Sun.cfg

Tbh don't know if we really need to heal +999

{FOREACH} replacement in Ascension and Toxic Sun

---

units/Demilich.cfg
utils/amla.cfg

Thunder + Demilich had "better chill tempest" advancement duplicated

Fix soul eater thunder, fix demilich duplicate advancement

---

utils/abilities.cfg

I forgot to expand the original issue #403 when I found that, it also doesn't work in keeps

Lesser nightstalk working in keeps

---

.github/scripts/upload_beta_addon.sh

The 1.17 addon server has been opened

Start uploading beta to 1.17.x server

---

utils/chapter9_utils.cfg

Fix typo "imact" instead of impact

---

utils/abilities_events.cfg
utils/global_events.cfg

This one's untested, since I don't have any save files to work from right now.

Lesser redeem doesn't work on bosses anymore. Fix #408.

---

lua/items.lua
scenarios1/00_Tutorial.cfg

It's easy to misread these, especially for something like Beyond Death, where increases and decreases are mixed together in a big list.

Different colors for increased and decreased in item descriptions

---

scenarios4/08_An_Army_Is_Born.cfg

It was my only wraith, the disappearance was quite noticeable.

Starter ghost in ch4's An Army Is Born carries over to next scenario.

---

utils/abilities.cfg

fix https://github.com/Dugy/Legend_of_the_Invincibles/issues/427

fix Precious Eagle Cactus Fruit doesn't give heals +40 if its bearer a healer himself

---

units/Goblin_Ravager.cfg

Goblin Ravager abandoned his wolf and rides a spider, so his race is monster

Goblin Ravager is a monster

---

utils/abilities.cfg

It was a bit of an unpleasant surprise starting ch8 with Eidolon's sword for Efraim.

Made unknown demon infiltrators susceptible to unholybane.

---

scenarios2/01_The_Beginning.cfg
scenarios2/05_Umbra.cfg
scenarios2/08_Sightseeing.cfg
scenarios3/01_Thirst_for_Adventures.cfg
scenarios3/01b_Bandits.cfg
scenarios4/11_Invasion.cfg
scenarios4/12_Bloodbath.cfg
utils/abilities_events.cfg
utils/items.cfg

Do I leave it as a draft? Possibly there are more such omissions throughout the campaign. Or do you prefer to fix its as I find them?

Omitted translatable strings

---

units/Delly_lich.cfg

Delly is a female Preserved lich

---

units/Akula.cfg

To differentiate it from other appearances of Unknown in male.

Akula female type

---

scenarios5/07_Into_the_Shadows.cfg

I noticed that the ally appears already incinerated, the effect she had when I killed her, so I added the same deletion that does the event where the incineration heals.

Remove incineration on thankful_enemy

---

units/hybrids_of_steel.cfg

Omission in female versions of steel hybrids

Female hybrids of steel

---

utils/chapter5_utils.cfg

What do you think about this? I did it for myself, for comfort. It will only look like this in 1920*1080, but it's optional.
https://github.com/Dugy/Legend_of_the_Invincibles/assets/40789364/110a4cc0-5055-4bf1-a30b-a3736e52cc9c

Option to enlarge map on chapter 5

---

units/hybrids_of_steel.cfg

Another little cosmetic fix. The Grand Marshall has no visible indication of its tentacle power, so it adds a special note just like the royal guard.

Add tentacle special note to Grand Marshall too

---

lua/inventory/items.lua
lua/items.lua
scenarios1/00_Tutorial.cfg
scenarios1/08_Where_the_Sun_Does_not_Shine.cfg
scenarios1/09_Escape_from_Oblivion.cfg
scenarios10/12_Rush.cfg
scenarios10/13_Black_Souls.cfg
scenarios10/14_End_of_the_World.cfg
scenarios4/08_An_Army_Is_Born.cfg
scenarios4/09_The_First_Blow.cfg
scenarios4/10_Dealing_with_Trolls.cfg
scenarios4/11_Invasion.cfg
scenarios4/17_Any_Means_Necessary.cfg
scenarios8/05_Investigations.cfg
utils/chapter5_utils.cfg
utils/chapter9_utils.cfg
utils/utils.cfg

tested where possible, though in a couple cases I can't find anything that would actually trigger the piece of code in question

Deprecated

---

scenarios6/03_Into_the_Light.cfg
scenarios6/05_Friends_No_More.cfg
scenarios6/09_Across_the_Barren_Land.cfg
scenarios6/14_Frozen_Land.cfg

08:09:27 info deprecation: FOREACH has been deprecated indefinitely.; You should use the [foreach] WML tag instead.
These have all been tested to at least perform equivalently to the previous versions (I don't think 03 works as intended, but not due to these changes, see https://github.com/Dugy/Legend_of_the_Invincibles/issues/517).

{FOREACH} => [foreach]/[for]

---

utils/abilities_events.cfg

Sorry, I did not send the last PR correctly, It did not have the last fix I did after the testing.

Devastating blow formula fix

---

utils/abilities.cfg

Despite the fact that many weapons indicate whether their use can be offensive or defensive, these do not have such a clarification. I include these using the same style as the others. Seem to you? Translating I realized that there were many like this.
If anyone knows of any other, I can include.
Note: In parry "When a defender target misses" means that if the defender of YOUR attack misses, so offensively only. I hope it is well understood.

Offensively weapons descriptions

---

utils/chapter9_utils.cfg

requires >= 1.15.10
tested on 1.16.2
code just below this uses old distance result to set limits, so might need to tweak
I needed a distraction and ran into this comment while looking for something else.
There's also an abs now, fwiw

use new wml sqrt

---

utils/abilities_events.cfg
utils/redeeming.cfg

To avoid an exploit in chapter 9

Revert redeeming reset on #545

---

units/corruption.cfg

Includes fighter, warrior and myrmidon using preprocessor #ifver
Tested on both versions
Solves #547

Corrupted Naga compatible with 1.17.4+

---

lua/redeem.lua
scenarios10/14_End_of_the_World.cfg
scenarios6/15_Apologies.cfg
scenarios8/03_United.cfg
scenarios8/14_Finally_Together.cfg
scenarios9/01_Transporting_Facility.cfg
utils/redeeming.cfg

Just the one commit 5870989, clearing a couple variables.
I wanted to nuke that section and replace it with a very small for loop, but it scares me.

Clear a couple variables

---

utils/abilities.cfg
utils/utils.cfg

Hm, it happened still not fixed. Also I moved it to utils.cfg, I think it makes there more sense than in abilities.cfg

Fix broken tags in REMOVE_TRAIT_BY_ID

---

lua/items.lua
scenarios9/30_Nightmare_Cellar.cfg
utils/global_events.cfg

Created RARE_ITEM_TURN allowing setting of turn value for dropped item
I don't think I like optional arguments passed as an ordered list (to lua function).  If I were doing this from scratch, I think I'd rather pass a table with arguments declared explicitly.  But I don't have the XP to make that argument now, best to leave it alone.
Ref #527

Nightmare Cellar

---

lua/inventory/storage.lua
lua/item_pick.lua

Last night I picked up Lilith's Precious sword and smashed it to get a random gem.  Lilith was right there, she had to have seen me do it, and yet she said NOTHING.

fix missing dialog

---

spinoffs/The_Beautiful_Child/units/Magic_Missile.cfg
spinoffs/The_Beautiful_Child/units/Reezer.cfg
spinoffs/The_Beautiful_Child/utils/global_events.cfg
spinoffs/The_Beautiful_Child/utils/rpg_events.cfg
spinoffs/The_Beautiful_Child/utils/strategy_events.cfg
spinoffs/The_Beautiful_Child/utils/utils.cfg

Using the improved wmlgettext tool from the latest version 1.17.18, I have found several typos.
By the way, are these three separate campaigns still being updated or are they already obsolete?

Typo on the Beautiful Child textdomain

---

utils/chapter9_utils.cfg

I don't understand this part of the code, I was just in there replacing FOREACH and this didn't look right.

potential typo

---

units/Phoenix.cfg

Images were not found because of missed ".png"

Fix phoenix death halo

---

utils/abilities_events.cfg

I remembered that neither Point of Sacrifice nor Krux's ability didn't work in my games, looked at it now, fixed the wrong if condition that prevented it from adding wrath except for the first time

Fix matryrdom only triggering for one hit

---

lua/items.lua

I remember long time ago they were visible. now only description

Make potions' flavours visible

---

lua/utils.lua
utils/soul_eater.cfg

Replace FOREACH statements
use new [is_in_list] from lua/utils.lua I improperly added yesterday to collapse big if/or block.
Tested over several advancements in part 1.

remove FOREACH, use [is_in_list]

---

scenarios3/11_Achilles_Revenge.cfg

I don't know who is supposed to be speaking, if it matters, but second_unit wasn't working.

fix missing speaker

---

scenarios3/12_Bitter_Swamp.cfg

I figured unit would be the unit who made the last kill, but I guess that doesn't make sense (could be ally/frenemy/incinerate,etc).
Anyway, the speaker was missing.  In the beginning, Delly says she hates swamps, so she seems like the obvious choice.

missing speaker

---

lua/utils.lua
utils/utils.cfg

A few times in ch4 you can recall previous units.  This sorts the list by name.
Will use this to clean up autorecall a bit once I get to ch5 and can test.

add [sort_unit_list]

---

utils/abilities_events.cfg
utils/autorecall.cfg
utils/chapter5_utils.cfg
utils/global_events.cfg
utils/utils.cfg

I can't say I tested every change, but I played all of part 1 with these.

Foreach utils

---

units/Uria_avatar.cfg

Don't understand why I didn't fix it in #372 (I fixed other variations but only animations here)

Fix Uria_avatar variations

---

scenarios1/10_The_Poison.cfg
scenarios2/10_Lilith.cfg
scenarios3/15s_Epilogue.cfg
scenarios5/01_Diplomacy.cfg
scenarios5/07_Into_the_Shadows.cfg
scenarios6/test_scenario.cfg
units/Elvish_Assassin.cfg
units/Uria.cfg
units/Vritra_later.cfg

Tested the 5 scenarios that I could.
Akula's comment in Diplomacy about not being able to swim is a little odd.  There's only a bit of deep water in an unused corner (it would make more sense if the river was deep water).  And of course, I immediately gave her Static Float, and got not so much as a thank you.  I don't think she's a very nice person.
In Lilith, Phobos speaks (giving away his location), though he's invisible
In Lilith, this does not work: (changed to id=)
speaker=Verderber,Nemesis,Phobos,Deimos
In Lilith, comment says when 3 of the councilors die.  It only takes 2 if they die before Corruptia.

replace FOREACH

---

scenarios1/03_Banished.cfg

gold carryover ch1

---

scenarios10/13_Black_Souls.cfg

Couldn't figure out how to re-open #617

Black Souls a little easier

---

utils/abilities_events.cfg

fix missing loop variable

---

utils/abilities_events.cfg

Found a typo, but fixing it broke things (I must have gotten lucky that all my tests went the right way, but for the wrong reasons).
Cleaned up some superfluous code ([and] tags, checking for status=incinerated and side for each case).
Tested every case I could think of.

fixes for incinerate cleanup

---

utils/abilities_events.cfg

Picked up this little gem from the forums.

improved remove incineration

---

lua/inventory/multiplayer_safety.lua

Replaced numerous string comparisons with a hash table lookup.

Minor performance optimization in mpsafety:run_immediately()

---

units/Efraim_lich-weakened.cfg
units/Lethalia_lich-weakened.cfg

Considering the discussion in #583, may propose this, buff them a bit (+5 hp, less xp to level on lower difficulties) and add one strike to basic faerie fire of Lethalia, that should prevent her from being stuck too much

Buff weaked Efraim and Lethalia

---

units/corruption.cfg

fix corrupted elvish fighter graphic

---

utils/abilities_events.cfg
utils/global_events.cfg

Fix #375 
Just started ch9, it'll be a while before I get to a scenario where I can test this.

Picking up gear on icy cave walls

---

lua/utils.lua

Renamed post 1.14.   Tested 1.16.10 and 1.17.25.

wesnoth.fire -> wml.fire

---

scenarios5/15_Amplificator2.cfg

xbow.png -> crossbow.png

---

lua/inventory/items.lua
lua/items.lua

Tested on chapters 1-6.
No immediate need for this, just removes warnings.

update dep lua functions

---

utils/chapter5_utils.cfg
utils/chapter9_utils.cfg

Looks a little nicer, allows one-click (or better yet just enter/escape) selection.

confirm go to scenario

---

utils/item_list.cfg

Okay, three different supported shades of blue.  I don't know if they're different enough to tell, but they don't error.
I couldn't find a list of supported colors, except for team colors.
Ref #703

cyan -> blues

---

scenarios1/01_An_Orcish_Assault.cfg

remove micro_ai

---

scenarios2/01_The_Beginning.cfg
scenarios2/02_Gods.cfg
scenarios2/04_Darkness_Closing_In.cfg
scenarios2/05_Umbra.cfg
scenarios3/14_Chasing_Dragons.cfg

Please also note the comments on gold/income for our side being higher on harder levels, particularly Chasing Dragons which is just ridiculously easy.

canrecrut -> canrecruit

---

utils/utils.cfg

If you've seen the monument, but not summoned bzb, she shouldn't say "bzb's here again", she should say "that rock is here again"

improve bzb momument sighted msgs

---

scenarios3/05_The_Pit.cfg

stop showing lose condition when it's no longer possible

fix objectives

---

scenarios3/09_Ambush.cfg

wish i knew how to combine these when using the web interface

fix gold objectives

---

scenarios4/04_Doomsday_Omens.cfg

correct sides

---

utils/item_list.cfg

When not clear, I assumed QUANTITY was correct.

 attribute to QUANTITY = HARD

---

lua/main.lua

Why do I always look for loti_harm_unit?

add kill= to harm_unit_loti

---

scenarios4/11_Invasion.cfg

Lines 105-108 in scenarios4/11_Invasion.cfg don't belong.  I pushed a second commit to clean them up, but I have no idea where it went.  EDIT: never mind, fixed

performance fix and tweaks

---

scenarios5/02_Escape.cfg

I'm trying to tweak the AI here so that, at least on hard, some of the enemy go after the boat (like E says they are in the beginning).  Of course, no progress there, I've yet to get anything to take effect on the ai.
But in playing around I have seen them kill the boat, which should result in a loss in any case.  Without forcing them to target it, you have to try really hard (be stupid enough) to get them to actually attack it, but they can.

defeat if boat destroyed

---

scenarios5/06_The_Real_Enemy.cfg

order of events for DROPS

---

utils/global_events.cfg

I want to disable fast_ai, but I only need to do so for side 3.  Also tested "2,3".  "yes" is still all sides.

have no_fast_ai accept a side list

---

utils/abilities.cfg

Rockbound Cave (Hills, Cave) - should be included since it's hills?

add hills/cave to lesser nightstalk

---

lua/redeem.lua

I was thinking about taking resist impact, but wasn't sure what my resistances were at the moment.  Now I know.

add unit preview to soul/redeem amla unlock

---

scenarios5/08_Entrance.cfg
utils/abilities_events.cfg

end tunnel transition abuse on hard

---

scenarios3/08_Lost.cfg

I misunderstood how this worked.

correct ability naming

---

units/demon_infiltrators.cfg
units/demon_infiltrators_unidentified.cfg

Fixes spearman/swordsman and provides an example for fixing others
Ref #686

1.17+ animations for demon spear/sword

---

scenarios9/30_Nightmare_Cellar.cfg
utils/abilities_events.cfg
utils/chapter9_utils.cfg

Nightmare Cellar:
Fixed Lilith's side so she appears
Moved statues slightly to provide a little separation and move unit out of wall.
Changed activation to use radius and proper locations.
The gender_X_Y variables can't be cleaned up properly, so I hid them under quests.  I have this thing about orphaned variables cluttering up the inspect gui.
Closes #796

lilith appears, statues awaken

---

units/demon_infiltrators.cfg

looks like this changed in 1.17

use current animation

---

lua/redeem.lua

I know I fixed this as some point.  Maybe it was in WML?

blizzart does not move units, unfortunately

---

scenarios1/00_Tutorial.cfg

fix items when skip tutorial
